### PR TITLE
Adapt to the changes in godot download page

### PR DESCRIPTION
**Pull request by Jeffrey04**
This is a minor patch to fix godot installation with umake. Long term fix would be introducing a proper html parser but for now this fix will do.

### CODE REVIEW

**Comment by Jeffrey04** [comment]
hmm the asset logo url is changed again, let me fix it

**Review by LyzardKing — CHANGES_REQUESTED** [review]
Looks good.
Change the regex to `href=\"?([^\s]+\.zip)` since we don't need the rest of the line parsed

**Comment by Jeffrey04** [comment]
> Looks good. Change the regex to `href=\"?([^\s]+\.zip)` since we don't need the rest of the line parsed
done

**Comment by LyzardKing** [comment]
Merged. Thank you for the fix

**Pull request merged**
