### PR TITLE
Version update

### LINKED ISSUE #74: Support updating tools
Ok, the Twitter website just crashed my Firefox while I was in the middle of writing this up, so this writeup is gonna be shorter. :p

Some tools can update themselves - stuff from PPAs, JetBrains, Eclipse, Android stuff I think. This doesn't concern these tools.

Some tools can't, like go-lang and probably any other language support we add in the future. We should have an upgrade workflow for these tools.

Actually upgrading the tools should be easy due to our policy of always getting the latest upstream - remove&install. What we should improve is the way users know what needs to be updated.

A subset of our tools should support reporting the version of a tool back. So when we install a tool, the version goes into the config file.

Then users can ask umake - list all tools that have updates. We go through all installed tools from the config file, check if their modules support versioning. If they do, fetch latest upstream version, compare with the current version (if current version is missing, because the tool was installed before we added support for versions, flag as 'update available') and list everything that can be updated.

### PR DESCRIPTION
**Pull request by LyzardKing**
Add --version and --update commands for supported frameworks.
This simply compares the installed version with the upstream available version.

The auto-updating frameworks would not be supported.
As an example, firefox-dev only returns the version.
Atom, Sublime-text and go are updatable

Fixes #74

### CODE REVIEW

**Comment by Xerus2000** [comment]
Guys I really want this to be in umake! Why is it still not merged and not even adressed?

**Comment by LyzardKing** [comment]
@Xerus2000 There has been ongoing work..
But as specified in the related issues, it's not something easy to implement.
It's updated, rebased on master...but it'll not be merged for the moment.

**Comment by LyzardKing** [comment]
The main issue is recreating the correct cli instrucions for an already installed framework.
We do not have access to the original arguments.

**Comment by Xerus2000** [comment]
well you could write them into the config file too, that seems to me like the easiest option

**Review by Tonymmm — APPROVED** [review]

**Pull request closed without merging**
