### PR TITLE
Unity3D on lts mesa updates

### PR DESCRIPTION
**Pull request by LyzardKing**
Added as possible dependencies mesa-lts
Closes: #253 

I'm not running ubuntu 14.04. If somebody could test this to see if we need to change other dependencies it would be good.

On ubuntu non lts it should stop at the first version (non lts); on 14.04 it should stop at the first available one. A problem could arise if there is no version installed. Is that possible?

### CODE REVIEW

**Comment by Alvarz** [comment]
I still have the error, is this already on the main branch?

**Comment by LyzardKing** [comment]
Not yet. I would prefer to test this, before merging. I'll setup a 14.04.4 vm and try it there. If you want you can test the branch.

**Comment by LyzardKing** [comment]
@Alvarz Did you test the branch?

**Comment by Alvarz** [comment]
@LyzardKing [#253](https://github.com/ubuntu/ubuntu-make/issues/253) here is the result of the tes, sadly it did'nt work for me

**Comment by LyzardKing** [comment]
@Alvarz Test the latest version. This should work.
I changed the order so it will install the latest mesa version, not the first available (the old ones remain available)
Let me know

**Comment by Alvarz** [comment]
@LyzardKing  Yeah pal It's worked like a charm!!! I have already unity thanks to you!.

So this brach actually works on ubuntu 14.04.3

**Comment by LyzardKing** [comment]
Great! I was really counting on this to work.
I wasn't too sure it would though. ;)
I'll merge then, so this can be in the next release.

**Comment by LyzardKing** [comment]
@Alvarz 
Sorry, there was a typo in the code. It should not make a difference, but could you test it once more?

**Comment by Alvarz** [comment]
Guys I think it had a big issue. It install unity 3d but after restart the SO stop working, dont boot, anything. When i hsd been looking throught the terminal i have many erros with libgl1-mesa-glx, libgl1-mesa-grid an all xserver* packages i  dont know if this was a coincidence or if this cause the error. I recommend do more tests on virtual machines

**Comment by Alvarz** [comment]
Sorry the typing errors Im on my mobile and its on spanish

**Comment by LyzardKing** [comment]
I'm sorry! I did test it in a vm without issues, but apparently it was set
up different from your system.
I'd say the problem is with the version of libgl1-mesa-glx we end up
selecting being different from the one in your system.
In your case nothing should have happened, since one of the supported
versions was already installed.

**Comment by Alvarz** [comment]
Yeah, I've already fixed my system but unity3d stuck on starting, I dont
know if is cause a some packages issue, or if is unity 3d itself. I will
dig on it

**Comment by LyzardKing** [comment]
I'd ask you to try the latest version (Fix typo), but I don't want to cause issues to your system.
Could you let me know what version of the kernel and enablement stack? 
Is your system a clean(ish) version of ubuntu 14.04.3?
So I can try and replicate a similar vm

**Comment by LyzardKing** [comment]
After some testing, I arrived at a possible conclusion.
Since the different versions of lts stack updates are all in 14.04 apt cache, they can conflict with one another.
I believe it's better to fail the install than to break a system.
None of the two should happen anyway, if we cover all possibilities.
So we should set the order from oldest to newest.
If a version is already installed (should be the case in ubuntu desktop) -> do nothing;
if no version is installed for some reason(I don't think it's possible) -> install the first (non-lts updated) or fail.
I think this is the best thing we can do for now.

**Comment by LyzardKing** [comment]
Yes. It should not be possible to have an ubuntu install with X, that is missing libgl1-mesa-glx from what I gather. So there should be no problems.
I'm still not sure about what the issue was on your system.

**Comment by didrocks** [comment]
I guess we are good then! +1 from my standpoint :)

**Comment by LyzardKing** [comment]
It should work. I'll test this on clean trusty installs in the next days to
be sure we 'we not breaking anything.
If those tests pass I'll merge.

**Comment by LyzardKing** [comment]
@Alvarz Did the last version work? Or did it cause any problem?
I'm trying to figure out what went wrong before merging

**Comment by LyzardKing** [comment]
Ok. xorg depends on libgl1-mesa-glx.
This means that a version of libgl1-mesa-glx has to be installed on your system.
This solves the doubt I had.
I'll merge now.

**Comment by Alvarz** [comment]
Hello Galileo I have been installed it throught the deb package from
unity3d website without any issue.

**Pull request merged**
