### PR TITLE
Change eclipse download-keyword to avoid conflicts

### LINKED ISSUE #328: ERROR: Download page changed its syntax or is not parsable
```bash
$ uname -a
Linux andres-ts 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ umake --version
16.05

$ umake -v ide eclipse
INFO: Logging level set to INFO
INFO: Create a new apt cache
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: Don't register Eclipse ADT as it's not installable on this configuration.
INFO: Don't register Dart Editor as it's not installable on this configuration.
INFO: libxpm4:i386 isn't installed
INFO: libxmu6:i386 isn't installed
INFO: libgtk2.0-0:i386 isn't installed
INFO: libatk1.0-0:i386 isn't installed
INFO: libcairo2:i386 isn't installed
INFO: libpango1.0-0:i386 isn't installed
INFO: libxcursor1:i386 isn't installed
INFO: libnss3-1d:i386 isn't installed
INFO: libnspr4-0d:i386 isn't installed
INFO: libcurl3:i386 isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: openjdk-7-jdk isn't installed
INFO: ruby isn't installed
INFO: openjdk-7-jre isn't installed
INFO: openjdk-7-jre isn't installed
Choose installation path: /home/andres/.local/share/umake/ide/eclipse
INFO: Start downloading DownloadItem(url='https://www.eclipse.org/downloads/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None) in memory
INFO: Starting new HTTPS connection (1): www.eclipse.org
INFO: https://www.eclipse.org/downloads/ download finished
INFO: All pending downloads for [DownloadItem(url='https://www.eclipse.org/downloads/', checksum=None, headers={'User-agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/41.0.2272.76 Chrome/41.0.2272.76 Safari/537.36'}, ignore_encoding=False, cookies=None)] done
ERROR: Download page changed its syntax or is not parsable
```

### PR DESCRIPTION
**Pull request by LyzardKing**
fixes #328 
umake was downloading the javascript version. Now it works.
The tests should be fine

---
This change is [Reviewable](https://reviewable.io/reviews/ubuntu/ubuntu-make/330)

### CODE REVIEW

**Comment by didrocks** [comment]
Looking good to me! Many thanks :)

**Comment by LyzardKing** [comment]
Now it should be good no matter what they change in the page layout.

**Comment by LyzardKing** [comment]
@didrocks ...any idea why test_decompressor is failing?

**Comment by didrocks** [comment]
This test is a little bit racy (my bad, I would need to have a serious look), just kicking it again

**Comment by LyzardKing** [comment]
..locally it doesn't fail. And I didn't change anything that could annoy it

**Comment by didrocks** [comment]
yeah, disregard it, I'll have a look at it later on :)

**Comment by didrocks** [comment]
yeah, disregard it, I'll have a look at it later on :)

**Comment by LyzardKing** [comment]
Ok. Merging then

**Pull request merged**
