### PR TITLE
Fix Rust downloads url

### LINKED ISSUE #337: Rust Install Broken
Rust seems to have changed their URL for the downloads page:

``
Rust Lang is already installed on your system, do you want to reinstall it anyway? [Yes (y)/No (N)] y
Choose installation path: /home/jravetch/.local/share/umake/rust/rust-lang
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/rust.py", line 98, in get_metadata_and_check_license
    link = (soup.find('div', class_="install")
AttributeError: 'NoneType' object has no attribute 'find'
``
The new URL is https://www.rust-lang.org/en-US/downloads.html

Since they added region selector, how do you want to handle this?

### PR DESCRIPTION
**Pull request by jravetch**
Fixes #337

### CODE REVIEW

**Comment by LyzardKing** [comment]
Great. Now all you need to do is change the location of the test files in tests/data/server-content to where the browser redirects you.

**Comment by jravetch** [comment]
@LyzardKing Should be fixed now.

**Comment by LyzardKing** [comment]
Do the tests work?

**Comment by jravetch** [comment]
Medium tests pass, please also confirm on your side.

**Comment by LyzardKing** [comment]
The mock webpage needs to be changed. The links for the linux version need to point to "static.rust-lang.org/...".

**Comment by jravetch** [comment]
Modified the links and moved the mock download files to static.rust-lang.org

**Comment by LyzardKing** [comment]
The medium test is failing. Is it working for you?

**Comment by jravetch** [comment]
Sorry about that.  Reverted the path change.  Medium tests pass now.

**Comment by LyzardKing** [comment]
Well, that change was needed. There must be something else that's wrong.
Could be the SSL certificate.
But keep the static.rust-lang change

**Comment by jravetch** [comment]
SSL cert seems to be a wilfcard now.  Do we need to change the crt?

**Comment by jravetch** [comment]
I get the following:

ERROR: https://static.rust-lang.org/dist/rust-fake-x86_64-unknown-linux-gnu.tar.gz.sha256 couldn't finish download: 404 Client Error: Not Found
ERROR: 404 Client Error: Not Found
CRITICAL: Exception in worker
Traceback (most recent call last):
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./umake/network/download_center.py", line 133, in _fetch
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found

**Comment by LyzardKing** [comment]
It could be that the existing certificate is not good for static.rust-lang.org
But I'm not sure. Do you mind trying to rebuild the docker image with a new key?

**Comment by jravetch** [comment]
Should I make the key for static.rust-lang.org?

**Comment by LyzardKing** [comment]
You could try to make it for rust-lang.org, to see if a generic one works..

**Comment by jravetch** [comment]
There is no root cert for rust-lang.org.  Only a wildcard for *.rust-lang.org

**Comment by jravetch** [comment]
Alight I got the tests working.  Generic cert didn't work, so I created one for static.rust-lang.org.  Added it  to the hosts list as well.  As this branch is getting messy, I'm gonna close this PR and open a new one.

**Pull request closed without merging**
