### PR TITLE
Arduino

### PR DESCRIPTION
**Pull request by Tinche**
Fix for #102.

Not yet ready for merging - need to write tests. It's feature complete though.

Had to implement some more functionality into the DownloadCenter - support for final_url (the final URL after all redirections), and cookie support for both requests and responses.

### CODE REVIEW

**Comment by Tinche** [comment]
Also, going by @mhalano's comment and http://playground.arduino.cc/linux/ubuntu, looks like we need to depend on gcc-avr and avr-libc, and add the user to the dialout group.

**Comment by mhalano** [comment]
@Tinche Dependencies and add to group is a problem which can be solved?

**Comment by Tinche** [comment]
Of course :) Just need to get around to it.

**Comment by didrocks** [comment]
Looking great! Nice work Tinche ;)

Yeah, adding to the group is fine, maybe, we need to add a hook for requiring root:
- if some packages are required and not installed, root will be required (this is already handled).
- maybe we can add a hook from the BaseFramework: look at self.need_root_access in __init__(). I would call a generic (doing a no-op in BaseFramework) hook. Then, in the arduino framework, using that hook to requiring root if the user isn't in the dialout group. I'm happy to help on this if needed.

Adding some more comments inline for this first review before testing.

**Comment by Tinche** [comment]
Thanks for the comments, @didrocks ! I still need to get around to the group adding hook and tests. Might take a little while, it's the middle of a busy work week :)

**Comment by didrocks** [comment]
No hurry at all (I won't be available on Thursday anyway) ;) Great work!

**Comment by Tinche** [comment]
So, the status of this issue is what everything is done except:

* adding the user to the dial group (maybe you could take a look, @didrocks, since you had an idea of how to do this in a reusable manner)
* the medium (Docker) test

I've put in some work on the medium test, but I can't get it to pass since the large test it's based on depends on accessing the desktop file inside the container (_get_path_from_desktop_file, assert_exec_exists, assert_icon_exists). I see other medium tests use these, so I'm guessing the other medium tests don't work either?

Honestly, when I'm working on adding something new, I spend a disproportionate amount of time on the medium test alone. At this point I'm wondering if it's worth it.

**Comment by didrocks** [comment]
Looking good! (just look at your recent commits)

I guess they still worths it, unfortunately, nothing in Ubuntu CI is currently capable of running them. I'll still work on those, don't worry :)

I'm on a sprint next week, so I may be able to start looking at this, but I guess the final touch will be the following wekk. I'll fork your branch and add the group thingy.

Thanks again for your hard work!

**Comment by didrocks** [comment]
I've fixed all medium test issues in trunk, merging now your PR and adding the medium test + dialout group addition!

Thanks again for your work, I'll probably release it after my holidays, so staging it a little bit in trunk first!

**Pull request merged**
