### PR TITLE
Add spring tools

### PR DESCRIPTION
**Pull request by LyzardKing**
Rebuilt copying the eclipse custom downloader.
The large test works. The medium test fails, with the error:
umake ide: error: argument framework: invalid choice: 'spring-tools-suite'

### CODE REVIEW

**Comment by LyzardKing** [comment]
@didrocks Any idea why the mediumt test fails?

**Comment by didrocks** [comment]
This is typical that you don't have the correct packages available in the docker container. So, packages are not available to be installed -> framework not available to the user on this arch/configuration.

You can start the container by hand and inspect its content via apt-cache policy for instance and looks at required packages.

**Comment by LyzardKing** [comment]
you're right. They were looking for a mock repo called eclipse, but for eclipse we use android.
So now all the tests work.

**Comment by didrocks** [comment]
\o/

**Comment by didrocks** [comment]
That looks good to me! Let's merge it :)

**Pull request merged**
