### PR TITLE
Fix Rust download url

### PR DESCRIPTION
**Pull request by jravetch**
- Update Rust downloads URL
- User static.rust-lang.org for all asset downloads
- Add SSL certificate and key for static.rust-lang.org
- Update Dockerfile with new cert
- Update tests with new path

### CODE REVIEW

**Comment by jravetch** [comment]
@LyzardKing @didrocks This PR should be ready now.  Once approved and merged please update the Docker image.

**Comment by LyzardKing** [comment]
ERROR: https://static.rust-lang.org/dist/rust-fake-x86_64-unknown-linux-gnu.tar.gz.sha256 couldn't finish download: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

**Comment by LyzardKing** [comment]
Great! Everything works now

**Comment by LyzardKing** [comment]
Closes #337

**Pull request merged**
