### PR TITLE
Add Processing support

### PR DESCRIPTION
**Pull request by LyzardKing**
Add the software sketchbook program (https://processing.org/)

### CODE REVIEW

**Comment by didrocks** [comment]
This looks good to me! Is it still ready for merging to you?

**Comment by LyzardKing** [comment]
I'll give another go at the tests after the phantomjs one is done.
(I have to rebuild the docker image...)

**Comment by LyzardKing** [comment]
An issue has come up. The process to kill in the large test is (a java process) called "processing.app.Base".
In the large test I can use that in check_and_kill_process and everything works.
But how can I do that in the medium test?

**Comment by didrocks** [comment]
Look at other frameworks, like android or intellij ones. As part of the assets, there are multiple processes (basically one binary calling another one) with the correct naming. You can use this technic, no?

**Comment by LyzardKing** [comment]
I tried to look at the arduino tests, since apparently it uses processing.app.Base.
But I can't get it to work. Am I missing something?

**Comment by LyzardKing** [comment]
Might have forgotten to make java-fake executable...

**Comment by LyzardKing** [comment]
And done.

**Comment by didrocks** [comment]
Ahah :)

**Comment by didrocks** [comment]
Everything looks good, let's merge!

**Pull request merged**
