### PR TITLE
Update eclipse to use new urls

### PR DESCRIPTION
**Pull request by redmcg**
It looks likes Eclipse changed their URLs again. I used the following changes to get it to work.

### CODE REVIEW

**Comment by redmcg** [comment]
This should probably be a single commit rather than four. Let me know if you want me to merge these commits in to one and resubmit a new pull request.

**Comment by LyzardKing** [comment]
Thanks for the fix!

Does it work if you replace &mirror_id=1 with &r=1?
It was changed because some urls were broken, but it would be better
to use the second, since it should pick the best mirror

**Comment by LyzardKing** [comment]
Do you mind also trying the other eclipse ides?
The one that usually fails is eclipse-jee

**Comment by redmcg** [comment]
The one I did install was eclipse-jee - but I'll try the others and report back

**Comment by LyzardKing** [comment]
Good to know that eclipse-jee is working.
You can run the tests to check if everything is working.
If you can run the large tests, and the medium ones (but they require docker)

**Comment by redmcg** [comment]
I ran `./runtests tests.large.test_ide` and whilst the summary at the end said a number of tests failed - I don't think any of them were eclipse related (I'm not familiar at all with the tests or their output so my interpretation could be wrong).

Here's an extract from the debug logs which (I think) show the successful eclipse installs:
```
debug.log.15:2018-08-06 12:29:39,962 [umake.decompressor] INFO: Requesting decompression to /home/brendan/.local/share/umake/ide/eclipse-php
debug.log.15:2018-08-06 12:29:39,962 [umake.decompressor] DEBUG: Extracting to /home/brendan/.local/share/umake/ide/eclipse-php
debug.log.15:2018-08-06 12:29:41,550 [umake.decompressor] INFO: Decompression to /home/brendan/.local/share/umake/ide/eclipse-php finished
debug.log.15:2018-08-06 12:29:41,550 [umake.decompressor] INFO: All pending decompression done to ['/home/brendan/.local/share/umake/ide/eclipse-php'] done.
debug.log.16:2018-08-06 12:27:54,348 [umake.decompressor] INFO: Requesting decompression to /home/brendan/.local/share/umake/ide/eclipse
debug.log.16:2018-08-06 12:27:54,348 [umake.decompressor] DEBUG: Extracting to /home/brendan/.local/share/umake/ide/eclipse
debug.log.16:2018-08-06 12:27:55,836 [umake.decompressor] INFO: Decompression to /home/brendan/.local/share/umake/ide/eclipse finished
debug.log.16:2018-08-06 12:27:55,836 [umake.decompressor] INFO: All pending decompression done to ['/home/brendan/.local/share/umake/ide/eclipse'] done.
debug.log.17:2018-08-06 12:26:05,304 [umake.decompressor] INFO: Requesting decompression to /home/brendan/.local/share/umake/ide/eclipse-javascript
debug.log.17:2018-08-06 12:26:05,304 [umake.decompressor] DEBUG: Extracting to /home/brendan/.local/share/umake/ide/eclipse-javascript
debug.log.17:2018-08-06 12:26:06,675 [umake.decompressor] INFO: Decompression to /home/brendan/.local/share/umake/ide/eclipse-javascript finished
debug.log.17:2018-08-06 12:26:06,676 [umake.decompressor] INFO: All pending decompression done to ['/home/brendan/.local/share/umake/ide/eclipse-javascript'] done.
debug.log.18:2018-08-06 12:24:23,757 [umake.decompressor] INFO: Requesting decompression to /home/brendan/.local/share/umake/ide/eclipse-jee
debug.log.18:2018-08-06 12:24:23,757 [umake.decompressor] DEBUG: Extracting to /home/brendan/.local/share/umake/ide/eclipse-jee
debug.log.18:2018-08-06 12:24:26,581 [umake.decompressor] INFO: Decompression to /home/brendan/.local/share/umake/ide/eclipse-jee finished
debug.log.18:2018-08-06 12:24:26,582 [umake.decompressor] INFO: All pending decompression done to ['/home/brendan/.local/share/umake/ide/eclipse-jee'] done.
debug.log.20:2018-08-06 12:21:55,767 [umake.decompressor] INFO: Requesting decompression to /home/brendan/.local/share/umake/ide/eclipse-cpp
debug.log.20:2018-08-06 12:21:55,767 [umake.decompressor] DEBUG: Extracting to /home/brendan/.local/share/umake/ide/eclipse-cpp
debug.log.20:2018-08-06 12:21:57,407 [umake.decompressor] INFO: Decompression to /home/brendan/.local/share/umake/ide/eclipse-cpp finished
debug.log.20:2018-08-06 12:21:57,407 [umake.decompressor] INFO: All pending decompression done to ['/home/brendan/.local/share/umake/ide/eclipse-cpp'] done.
```
I also tried the medium tests - but these all failed with pretty much the same Exception stack:
```
Traceback (most recent call last):
  File ".../ubuntu-make/tests/medium/test_web.py", line 58, in setUp
    super().setUp()
  File ".../ubuntu-make/tests/medium/__init__.py", line 102, in setUp
    self.container_id = subprocess.check_output(command).decode("utf-8").strip()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1258, in _execute_child
    executable = os.fsencode(executable)
  File ".../ubuntu-make/env/lib/python3.6/os.py", line 800, in fsencode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
I've spent some time trying to resolve it, but so far, without success.

Let me know if you need anything else.

**Comment by redmcg** [comment]
I worked out the problem with the medium tests. I just needed to install the `docker.io` package (I had only installed the `docker` package :man_facepalming:). I'll run these when I get a chance and provide the results.

**Comment by LyzardKing** [comment]
The problem with the medium tests is that they rely on a mock of the server content...
In tests/data/server-content you can find the relevant parts of the websites and a fake archive to download.
I tried adding your patch to a branch I have where I replace some overrides.
I'm not sure however how to fake the urls that have a ...something.php?etc...

**Comment by LyzardKing** [comment]
You can launch a single test if you want. Just add the relevant class name like:
./runtests tests/large/test_ide.py:TestClass

**Comment by LyzardKing** [comment]
This is the branch: https://github.com/ubuntu/ubuntu-make/tree/github

**Comment by LyzardKing** [comment]
If you can fix the mock on your branch then it'll work on the other one as well.
Let me know if you can figure it out. And also if you need some information

**Comment by redmcg** [comment]
I'll look in to the mock sever content. But I might just ditch my branch and start using yours (although if it's easier I can check the changes in to here too).

Is the SHA512 used just for checking file integrity, or for authenticity too? If it's for authenticity, it might be worth using https to retrieve the SHA value (for assurance of its authenticity).

**Comment by LyzardKing** [comment]
The repo is now at #564 
We can also get eclipse in for now, if we can fix the medium tests.
Then we can work on the other repo.

**Comment by redmcg** [comment]
> I'm not sure however how to fake the urls that have a ...something.php?etc...

I found the following code which removes anything before `?file=`. So that's why `sums.php?file=` and `download.php?file=` end up getting the same file.
https://github.com/ubuntu/ubuntu-make/blob/0b53f5f5f93364418108de3d56557951d30cfb96/tests/tools/local_server.py#L201-L204

I changed line 202 to be:
```
if '?file=' in self.path and '/downloads/sums.php?file=' not in self.path:
```
and that allowed the file at `tests/data/server-content/www.eclipse.org/downloads/sums.php?file=/technology/epp/downloads/release/version/point_release/eclipse-java-linux-gtk-x86_64.tar.gz` to be downloaded.

But now I'm getting a different error:
```
ERROR: http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/version/point_release/eclipse-java-linux-gtk-x86_64.tar.gz&r=1 couldn't finish download: 'NoneType' object has no attribute 'name'
```
I haven't worked out what this one is about yet - but it could be related to the fact I had to change the environment `PATH` used within docker to put `/bin/usr` at the front. This is because the `python3` exec in the umake environment couldn't run.  The error was related to LIBC versions - most likely because docker is running `trusty` whilst I built the umake environment in `bionic`.

**Comment by LyzardKing** [comment]
...docker should use the proper versions.
it should download my docker image, and that should work.
Don't override anything in docker.

**Comment by redmcg** [comment]
I created a new pull request: #566. This builds on PR #564 to allow the medium and large Eclipse tests to complete successfully. As a result - I believe this PR can be closed.

**Comment by redmcg** [comment]
To clarify the `PATH` environment work-around I mentioned in one of my previous comments - if within the docker environment I tried the following - it would fail:
```
# /umake/env/bin/python3 -V
/umake/env/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /umake/env/bin/python3)
```
This is because the GLIBC version in the docker environment is 2.19:
```
# /lib/x86_64-linux-gnu/libc.so.6
GNU C Library (Ubuntu EGLIBC 2.19-0ubuntu6.14) stable release version 2.19, by Roland McGrath et al.
```
where as the following would work:
```
# /usr/bin/python3 -V
Python 3.4.3
```

When the medium tests run the local web-server, they use their own PATH environment:
```
.../ubuntu-make/tests/tools/run_in_umake_dir_async /umake 'sudo -E env PATH=.../ubuntu-make/env/bin:.../.local/share/umake/bin:.../.local/share/umake/android/android-sdk/tools:.../.local/share/umake/android/android-sdk/tools/bin:.../.local/share/umake/android/android-platform-tools/platform-tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin VIRTUAL_ENV=.../git/ubuntu-make/env .../git/ubuntu-make/tests/tools/run_local_server 443 False www.eclipse.org';
```
And because the first entry in the path is `.../ubuntu-make/env/bin` - it was trying to use the version of `python3` that is broken - hence the web-server would not run.

As a work around, I changed the `PATH` environment in the above command to have `/usr/bin` as the first entry. So this doesn't impact the entire docker environment, just the environment used by the web-server(s).

**Comment by redmcg** [comment]
This PR is now redundant

**Pull request closed without merging**
