### PR TITLE
added openjdk-8-jdk as a dependency to eclipse and jetbrains

### PR DESCRIPTION
**Pull request by LyzardKing**
Added openjdk-8 to eclipse and jetbrains ides.
Just want to be sure of a few things:
1. Are we sure that there are no issues with jdk-8? (there shouldn't be)
2. should we reintroduce jayatana?
3. Do the eap versions of jetbrains ides have the custom jdk?

### CODE REVIEW

**Comment by Tinche** [comment]
As noted before, JetBrains stuff doesn't need openjdk any more. Maybe remove it completely?

**Comment by LyzardKing** [comment]
Thanks! That's what I wanted to know. :)
Is that true for every jetbrains release?
If so I'll change it.

**Comment by Tinche** [comment]
PyCharm for sure (been using it), Idea Community Edition too (just
installed now to test).

**Comment by didrocks** [comment]
Let's do that then! (on jayatana: until we have a better story and it's tested, let's not include it)

**Pull request closed without merging**
