### PR TITLE
Add insiders build for vscode

### PR DESCRIPTION
**Pull request by overbid**
No test, somebody help me pls.

---

This change is [Reviewable](https://reviewable.io/reviews/ubuntu/ubuntu-make/320)

### CODE REVIEW

**Comment by overbid** [comment]
I add test and it's work fine.

**Comment by LyzardKing** [comment]
Looks good.
Do you have the medium tests as well?
I'm from my phone, so I can't really see properly.
In tests/large/tests_ide.py the lighttable test has the wrong indentation. Could you fix that?

**Comment by overbid** [comment]
I need guideline for the medium tests. And I think travis-ci don't work properly.

**Comment by LyzardKing** [comment]
Hi!
I haven't been around in a while. For the medium tests you can have a look at the intellij eap (#255).
You should be fine adding the fake files in the mock server...
I'll have another look at it in the next days and after the medium tests are in this can be merged.

**Comment by Tinche** [comment]
Think this would be useful to have. I can pull it over the finish line if need be, but only in a few weeks (totally swamped atm).

**Comment by LyzardKing** [comment]
Once the large tests work and the framework is complete, adding the medium tests should be easy.
The only thing you need to do is create the files pointing to the tarfiles.
In this case you can create symlinks to
`tests/data/server-content/go.microsoft.com/fwlink/visual-studio-code-amd64.zip`
as
`tests/data/server-content/go.microsoft.com/fwlink/?LinkId=723968`
and 
`tests/data/server-content/go.microsoft.com/fwlink/visual-studio-code-i386.zip`
as 
`tests/data/server-content/go.microsoft.com/fwlink/?LinkId=723969`

**Comment by LyzardKing** [comment]
@overbid @Tinche Any news on this? We should build a new release in a while, so I'm trying to solve as many pull requests as possible.

**Comment by Tinche** [comment]
Sorry, I'm too busy elsewhere :(

**Comment by LyzardKing** [comment]
Merged in the PR #437

**Pull request closed without merging**
