### PR TITLE
Logic OR in dependency list

### PR DESCRIPTION
**Pull request by LyzardKing**
Add the possilibity to specify a dependency on one of n packages.
At least one of them has to be installed for the dependency to be met

Example. The Eclipse versions could depend on openjdk-8-jdk or openjdk-7-jdk (or even oracle-jdk).
All we need to do is specify an order.
The dependency on packages `"A | B | C"` would: ("|" being the or)

- check if one of them is installed
- if not install the first available.

### CODE REVIEW

**Comment by didrocks** [comment]
That looks correct! However, the "if not install the first available" is hidden in the global logic. I'm afraid we break it without realizing.

I suggest that we get more global tests case (the one installing the package in the chroot), with:
* The 2 alternatives available -> check only the first one is installed
* Only the 2nd alternative available -> check that the second is installed

Otherwise, the diff provides an elegant solution for me, avoiding duplication, good work!

**Comment by LyzardKing** [comment]
I added in the tests a check of the new bucket, created by removing the items with " | ", adding the correct one instead.

**Comment by didrocks** [comment]
Looking good on the tests itself!
However, I'm unsure about the assertion, I would prefer an assertEquals(). That way, if the test fail, instead of "False is not True", we will see the 2 list content which differs.

**Comment by LyzardKing** [comment]
You're right :)
Fixed now with assertEqual

**Comment by didrocks** [comment]
Looks good! feel free to merge it now :-)

**Comment by LyzardKing** [comment]
Thanks! :)
Now I think we should have a "guideline" on what the defaults should be.
For instance, the eclipse installers could depend on:
`["openjdk-8-jdk | openjdk-7-jdk | [the oracle version?]"]`

or we could keep openjdk-7-jdk as the first one.

I'll merge this  now.

It would be interesting, if possible, to know what versions people are using.

**Comment by didrocks** [comment]
yeah, basing on data would be the best! I would say, let's try to keep the same base version as long as it's not required otherwise for upstream, for the sake of not creating issue on some configurations and not on others

**Comment by LyzardKing** [comment]
Sounds perfect! I'll merge this for now, and the next thing will be to change the dependencies to:
`["openjdk-7-jdk | openjdk-8-jdk"]` for the various eclipse/jetbrains/android(?).
I'll check to see if they support openjdk-8 first to be sure.
Then if somebody uses the oracle version we can add that as well.

**Comment by didrocks** [comment]
sounds like a good plan :)

**Pull request merged**
